import Head from 'next/head'
import Image from 'next/image'
import { InferGetStaticPropsType } from 'next'
import styles from '../styles/Home.module.css'
import { Palette } from '../types/palette'
import Chip from '../components/chip';

const API_URL: string = 'http://www.colourlovers.com/api/palettes/new?format=json';
var date: any, palettes: Palette[];

function Home({ palettes, date }: InferGetStaticPropsType<typeof getStaticProps>) {

  // setInterval(() => {
  //   refresh();
  // }, 5)

  return (
    <div className={styles.container}>
      <Head>
        <title>ColourLovers Live</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href='http://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'></link>
      </Head>

      <header className={styles.title}>
        <p>ColourLovers.  <a href="https://www.colourlovers.com/">Live.</a></p>
      </header>
      <sub className={styles.time}>Last Updated at {date}</sub>

      <main className={styles.main}>
        <div className={styles.grid}>

        {palettes.map((res: Palette) => (
          <a className={styles.card} key={res.id}>
              <h2>{res.title}</h2>
              <p>by {res.userName} at {new Date(res.dateCreated).toLocaleTimeString([], {hour: "numeric", minute:'2-digit'})}</p>

              <span className={styles.palette}>
                <Image src={res.imageUrl} alt={JSON.stringify(res.id)} width={96} height={96} />
              </span>

              <span className={styles.chiplist}>
                <Chip p={res} />
              </span>
          </a>
          ))}

        </div>
      </main>

    </div>
  )
}

export async function getStaticProps() {
  
  const res = await fetch(API_URL, { method: 'GET', 
                                headers:{'Content-Type': 'application/json', 'User-Agent': '*'}})
  date = new Date().toLocaleTimeString([], {hour: "numeric", minute:'2-digit'});
  palettes = await res.json();

  return {
    props: {
      palettes,
      date
    }
  }
}

export default Home